aws_access_key = "AKIA35Y4PIEJVPZALVEE"
aws_secret_key = "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"
key_name = "FirstKey"
private_key_path = "D:\\GitTest\\alinaopsschool\\terraform-begin\\FirstKey.pem"
html_page_path = "D:\\GitTest\\alinaopsschool\\terraform-begin\\index.html"